# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DynamicBackground(object):
    def setupUi(self, DynamicBackground):
        DynamicBackground.setObjectName("DynamicBackground")
        DynamicBackground.resize(799, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DynamicBackground.sizePolicy().hasHeightForWidth())
        DynamicBackground.setSizePolicy(sizePolicy)
        DynamicBackground.setMinimumSize(QtCore.QSize(799, 539))
        self.centralwidget = QtWidgets.QWidget(DynamicBackground)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.preview = QtWidgets.QGraphicsView(self.centralwidget)
        self.preview.setMinimumSize(QtCore.QSize(535, 0))
        self.preview.setObjectName("preview")
        self.gridLayout.addWidget(self.preview, 0, 0, 1, 2)
        self.run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout.addWidget(self.run_btn, 1, 0, 1, 1)
        self.generation_progress = QtWidgets.QProgressBar(self.centralwidget)
        self.generation_progress.setProperty("value", 0)
        self.generation_progress.setObjectName("generation_progress")
        self.gridLayout.addWidget(self.generation_progress, 1, 1, 1, 1)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setMinimumSize(QtCore.QSize(194, 0))
        self.toolBox.setObjectName("toolBox")
        self.gif_vars = QtWidgets.QWidget()
        self.gif_vars.setGeometry(QtCore.QRect(0, 0, 233, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gif_vars.sizePolicy().hasHeightForWidth())
        self.gif_vars.setSizePolicy(sizePolicy)
        self.gif_vars.setMinimumSize(QtCore.QSize(14, 0))
        self.gif_vars.setObjectName("gif_vars")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gif_vars)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gif_vars)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 9, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_5 = QtWidgets.QLabel(self.gif_vars)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 10, 0, 1, 1, QtCore.Qt.AlignRight)
        self.height_input = QtWidgets.QSpinBox(self.gif_vars)
        self.height_input.setObjectName("height_input")
        self.gridLayout_2.addWidget(self.height_input, 7, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gif_vars)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 5, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gif_vars)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 11, 0, 1, 1)
        self.gif_num_input = QtWidgets.QSpinBox(self.gif_vars)
        self.gif_num_input.setObjectName("gif_num_input")
        self.gridLayout_2.addWidget(self.gif_num_input, 9, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gif_vars)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 6, 0, 1, 1, QtCore.Qt.AlignRight)
        self.framerate_input = QtWidgets.QSpinBox(self.gif_vars)
        self.framerate_input.setObjectName("framerate_input")
        self.gridLayout_2.addWidget(self.framerate_input, 11, 1, 1, 1)
        self.generate_seed_btn = QtWidgets.QPushButton(self.gif_vars)
        self.generate_seed_btn.setMinimumSize(QtCore.QSize(129, 0))
        self.generate_seed_btn.setObjectName("generate_seed_btn")
        self.gridLayout_2.addWidget(self.generate_seed_btn, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gif_vars)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_7 = QtWidgets.QLabel(self.gif_vars)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 12, 0, 1, 1, QtCore.Qt.AlignRight)
        self.margin_input = QtWidgets.QSpinBox(self.gif_vars)
        self.margin_input.setObjectName("margin_input")
        self.gridLayout_2.addWidget(self.margin_input, 12, 1, 1, 1)
        self.seed_input = QtWidgets.QSpinBox(self.gif_vars)
        self.seed_input.setObjectName("seed_input")
        self.gridLayout_2.addWidget(self.seed_input, 2, 1, 1, 1, QtCore.Qt.AlignTop)
        self.frames_input = QtWidgets.QSpinBox(self.gif_vars)
        self.frames_input.setObjectName("frames_input")
        self.gridLayout_2.addWidget(self.frames_input, 10, 1, 1, 1)
        self.width_input = QtWidgets.QSpinBox(self.gif_vars)
        self.width_input.setObjectName("width_input")
        self.gridLayout_2.addWidget(self.width_input, 6, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gif_vars)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gif_vars)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.toolBox.addItem(self.gif_vars, "")
        self.point_vars = QtWidgets.QWidget()
        self.point_vars.setGeometry(QtCore.QRect(0, 0, 226, 630))
        self.point_vars.setObjectName("point_vars")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.point_vars)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.point_vars)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 14, 0, 1, 1)
        self.scale_input = QtWidgets.QDoubleSpinBox(self.point_vars)
        self.scale_input.setObjectName("scale_input")
        self.gridLayout_3.addWidget(self.scale_input, 2, 1, 1, 1)
        self.border_separation = QtWidgets.QSpinBox(self.point_vars)
        self.border_separation.setObjectName("border_separation")
        self.gridLayout_3.addWidget(self.border_separation, 12, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.point_vars)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.point_vars)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.border_right = QtWidgets.QCheckBox(self.point_vars)
        self.border_right.setObjectName("border_right")
        self.gridLayout_3.addWidget(self.border_right, 11, 1, 1, 1)
        self.border_left = QtWidgets.QCheckBox(self.point_vars)
        self.border_left.setObjectName("border_left")
        self.gridLayout_3.addWidget(self.border_left, 10, 1, 1, 1)
        self.drifting_percentage = QtWidgets.QDoubleSpinBox(self.point_vars)
        self.drifting_percentage.setObjectName("drifting_percentage")
        self.gridLayout_3.addWidget(self.drifting_percentage, 15, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.point_vars)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 7, 0, 1, 1)
        self.intensity_input = QtWidgets.QDoubleSpinBox(self.point_vars)
        self.intensity_input.setObjectName("intensity_input")
        self.gridLayout_3.addWidget(self.intensity_input, 1, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.point_vars)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 6, 0, 1, 2)
        self.separation_input = QtWidgets.QSpinBox(self.point_vars)
        self.separation_input.setObjectName("separation_input")
        self.gridLayout_3.addWidget(self.separation_input, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 14, 1, 1, 1)
        self.border_bottom = QtWidgets.QCheckBox(self.point_vars)
        self.border_bottom.setObjectName("border_bottom")
        self.gridLayout_3.addWidget(self.border_bottom, 9, 1, 1, 1)
        self.max_fails_input = QtWidgets.QSpinBox(self.point_vars)
        self.max_fails_input.setObjectName("max_fails_input")
        self.gridLayout_3.addWidget(self.max_fails_input, 5, 1, 1, 1)
        self.y_offset_input = QtWidgets.QSpinBox(self.point_vars)
        self.y_offset_input.setObjectName("y_offset_input")
        self.gridLayout_3.addWidget(self.y_offset_input, 3, 1, 1, 1)
        self.amplitude_input = QtWidgets.QDoubleSpinBox(self.point_vars)
        self.amplitude_input.setObjectName("amplitude_input")
        self.gridLayout_3.addWidget(self.amplitude_input, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.point_vars)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.point_vars)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 16, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.point_vars)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 12, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.point_vars)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 11, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.point_vars)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 15, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.point_vars)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 18, 0, 1, 1)
        self.drifting_x_min = QtWidgets.QSpinBox(self.point_vars)
        self.drifting_x_min.setObjectName("drifting_x_min")
        self.gridLayout_3.addWidget(self.drifting_x_min, 16, 1, 1, 1)
        self.drifting_y_min = QtWidgets.QSpinBox(self.point_vars)
        self.drifting_y_min.setObjectName("drifting_y_min")
        self.gridLayout_3.addWidget(self.drifting_y_min, 18, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.point_vars)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.point_vars)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.border_top = QtWidgets.QCheckBox(self.point_vars)
        self.border_top.setObjectName("border_top")
        self.gridLayout_3.addWidget(self.border_top, 8, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 9, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.point_vars)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 17, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.point_vars)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 13, 0, 1, 2)
        self.drifting_x_max = QtWidgets.QSpinBox(self.point_vars)
        self.drifting_x_max.setObjectName("drifting_x_max")
        self.gridLayout_3.addWidget(self.drifting_x_max, 17, 1, 1, 1)
        self.drifting_y_max = QtWidgets.QSpinBox(self.point_vars)
        self.drifting_y_max.setObjectName("drifting_y_max")
        self.gridLayout_3.addWidget(self.drifting_y_max, 19, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.point_vars)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 19, 0, 1, 1)
        self.toolBox.addItem(self.point_vars, "")
        self.triangle_vars = QtWidgets.QWidget()
        self.triangle_vars.setGeometry(QtCore.QRect(0, 0, 240, 351))
        self.triangle_vars.setObjectName("triangle_vars")
        self.triangle_type_combo_box = QtWidgets.QComboBox(self.triangle_vars)
        self.triangle_type_combo_box.setGeometry(QtCore.QRect(10, 10, 221, 28))
        self.triangle_type_combo_box.setObjectName("triangle_type_combo_box")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_type_combo_box.addItem("")
        self.triangle_args = QtWidgets.QWidget(self.triangle_vars)
        self.triangle_args.setGeometry(QtCore.QRect(10, 50, 221, 301))
        self.triangle_args.setObjectName("triangle_args")
        self.toolBox.addItem(self.triangle_vars, "")
        self.line_vars = QtWidgets.QWidget()
        self.line_vars.setGeometry(QtCore.QRect(0, 0, 240, 351))
        self.line_vars.setObjectName("line_vars")
        self.draw_lines_check_box = QtWidgets.QCheckBox(self.line_vars)
        self.draw_lines_check_box.setGeometry(QtCore.QRect(10, 10, 110, 26))
        self.draw_lines_check_box.setObjectName("draw_lines_check_box")
        self.line_type_combo_box = QtWidgets.QComboBox(self.line_vars)
        self.line_type_combo_box.setGeometry(QtCore.QRect(10, 40, 221, 28))
        self.line_type_combo_box.setObjectName("line_type_combo_box")
        self.line_type_combo_box.addItem("")
        self.line_type_combo_box.addItem("")
        self.line_args = QtWidgets.QWidget(self.line_vars)
        self.line_args.setGeometry(QtCore.QRect(10, 80, 221, 261))
        self.line_args.setObjectName("line_args")
        self.toolBox.addItem(self.line_vars, "")
        self.point_vars_2 = QtWidgets.QWidget()
        self.point_vars_2.setGeometry(QtCore.QRect(0, 0, 240, 351))
        self.point_vars_2.setObjectName("point_vars_2")
        self.point_type_combo = QtWidgets.QComboBox(self.point_vars_2)
        self.point_type_combo.setGeometry(QtCore.QRect(10, 40, 221, 28))
        self.point_type_combo.setObjectName("point_type_combo")
        self.point_type_combo.addItem("")
        self.draw_points_check_box = QtWidgets.QCheckBox(self.point_vars_2)
        self.draw_points_check_box.setGeometry(QtCore.QRect(10, 10, 118, 26))
        self.draw_points_check_box.setObjectName("draw_points_check_box")
        self.point_args = QtWidgets.QWidget(self.point_vars_2)
        self.point_args.setGeometry(QtCore.QRect(10, 80, 221, 261))
        self.point_args.setObjectName("point_args")
        self.toolBox.addItem(self.point_vars_2, "")
        self.gridLayout.addWidget(self.toolBox, 0, 2, 2, 1)
        DynamicBackground.setCentralWidget(self.centralwidget)
        self.action_triangle_color_chooser = QtWidgets.QAction(DynamicBackground)
        self.action_triangle_color_chooser.setObjectName("action_triangle_color_chooser")

        self.retranslateUi(DynamicBackground)
        self.toolBox.setCurrentIndex(2)
        self.triangle_type_combo_box.currentIndexChanged['int'].connect(self.action_triangle_color_chooser.trigger)
        QtCore.QMetaObject.connectSlotsByName(DynamicBackground)

    def retranslateUi(self, DynamicBackground):
        _translate = QtCore.QCoreApplication.translate
        DynamicBackground.setWindowTitle(_translate("DynamicBackground", "MainWindow"))
        self.run_btn.setText(_translate("DynamicBackground", "Run"))
        self.label_4.setText(_translate("DynamicBackground", "Gif Num"))
        self.label_5.setText(_translate("DynamicBackground", "Frames"))
        self.label_6.setText(_translate("DynamicBackground", "Framerate"))
        self.label_2.setText(_translate("DynamicBackground", "Width"))
        self.generate_seed_btn.setText(_translate("DynamicBackground", "Generate Seed"))
        self.label_3.setText(_translate("DynamicBackground", "Height"))
        self.label_7.setText(_translate("DynamicBackground", "Margin"))
        self.label.setText(_translate("DynamicBackground", "Seed"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.gif_vars), _translate("DynamicBackground", "Gif Variables"))
        self.label_16.setText(_translate("DynamicBackground", "Drifting Points"))
        self.label_10.setText(_translate("DynamicBackground", "Scale"))
        self.label_9.setText(_translate("DynamicBackground", "Intensity"))
        self.border_right.setText(_translate("DynamicBackground", "Right"))
        self.border_left.setText(_translate("DynamicBackground", "Left"))
        self.label_15.setText(_translate("DynamicBackground", "Border Points"))
        self.border_bottom.setText(_translate("DynamicBackground", "Bottom"))
        self.label_8.setText(_translate("DynamicBackground", "Amplitude"))
        self.label_18.setText(_translate("DynamicBackground", "X-Min"))
        self.label_14.setText(_translate("DynamicBackground", "Separation"))
        self.label_11.setText(_translate("DynamicBackground", "Y-Offset"))
        self.label_17.setText(_translate("DynamicBackground", "Percentage"))
        self.label_20.setText(_translate("DynamicBackground", "Y-Min"))
        self.label_12.setText(_translate("DynamicBackground", "Separation"))
        self.label_13.setText(_translate("DynamicBackground", "Max Fails"))
        self.border_top.setText(_translate("DynamicBackground", "Top"))
        self.label_19.setText(_translate("DynamicBackground", "X-Max"))
        self.label_21.setText(_translate("DynamicBackground", "Y-Max"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.point_vars), _translate("DynamicBackground", "Point Variables"))
        self.triangle_type_combo_box.setItemText(0, _translate("DynamicBackground", "Plain Color"))
        self.triangle_type_combo_box.setItemText(1, _translate("DynamicBackground", "Linear Gradient"))
        self.triangle_type_combo_box.setItemText(2, _translate("DynamicBackground", "Exponential Gradient"))
        self.triangle_type_combo_box.setItemText(3, _translate("DynamicBackground", "Discrete Gradient"))
        self.triangle_type_combo_box.setItemText(4, _translate("DynamicBackground", "Ambient Shader"))
        self.triangle_type_combo_box.setItemText(5, _translate("DynamicBackground", "Multi-light Shader"))
        self.triangle_type_combo_box.setItemText(6, _translate("DynamicBackground", "Gradient Shader"))
        self.triangle_type_combo_box.setItemText(7, _translate("DynamicBackground", "Static Noise"))
        self.triangle_type_combo_box.setItemText(8, _translate("DynamicBackground", "Tie Dye Swirl"))
        self.triangle_type_combo_box.setItemText(9, _translate("DynamicBackground", "Color Shifting"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.triangle_vars), _translate("DynamicBackground", "Triangle Coloring"))
        self.draw_lines_check_box.setText(_translate("DynamicBackground", "Draw Lines"))
        self.line_type_combo_box.setItemText(0, _translate("DynamicBackground", "Solid Line"))
        self.line_type_combo_box.setItemText(1, _translate("DynamicBackground", "Fading Line"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.line_vars), _translate("DynamicBackground", "Line Drawing"))
        self.point_type_combo.setItemText(0, _translate("DynamicBackground", "Plain Point"))
        self.draw_points_check_box.setText(_translate("DynamicBackground", "Draw Points"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.point_vars_2), _translate("DynamicBackground", "Point Drawing"))
        self.action_triangle_color_chooser.setText(_translate("DynamicBackground", "_triangle_color_chooser"))

